version: '3.3'
services:
  php:
    container_name: php
    build:
      context: docker/php
      dockerfile: php.Dockerfile
    volumes:
      - "./kaimonster:/var/www/html"
    tty: true
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    - "./docker/nginx:/var/log/nginx/"
    - "./kaimonster:/var/www/html"
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
#    restart: 'on-failure'
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "kai_db"
    volumes:
      - "./docker/mysql/db:/var/lib/mysql"
#      - "./docker/mysql/custom.cnf:/etc/mysql/conf.d/mysql.cnf"
#      - "./docker/mysql/query.log:/var/log/query.log"
      - "./kaimonster:/var/www/html"
    ports:
    - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: 'on-failure'